### PR TITLE
Fix no auto_bounds preventing pan/zoom/scroll

### LINKED ISSUE #151: Disabling default auto_bounds prevents pan/zoom/scroll
**Describe the bug**

When `auto_bounds(false)` is passed to the Plot object (setting the default auto_bounds behavior), any panning/zooming on that axis is immediately reverted, even though it should still be allowed.

**To Reproduce**

Minimal example:
```rust
let options = eframe::NativeOptions::default();
eframe::run_simple_native("Example", options, move |ctx, _frame| {
    egui::CentralPanel::default().show(ctx, |ui| {
        egui_plot::Plot::new("Plot1")
            .allow_drag(true)
            .allow_zoom(true)
            .allow_scroll(true)
            .auto_bounds(false)
            .show(ui, |ui| {
                ui.line(egui_plot::Line::new("line", vec![[0.0, 0.0], [1.0, 1.0]]));
            });
    });
})
```

**Expected behavior**

Plot should startup and reset with fixed default bounds (rather than autoscaling to data), but pan/zoom/scroll should still allow the user to change them interactively.

**Additional context**

From digging around a bit in the code I believe the following from `lib.rs:1104` is responsible:

```rust
// Reset bounds to initial bounds if they haven't been modified.
if (!default_auto_bounds.x && !any_dynamic_modifications) || mem.auto_bounds.x {
    bounds.set_x(&min_auto_bounds);
}
if (!default_auto_bounds.y && !any_dynamic_modifications) || mem.auto_bounds.y {
    bounds.set_y(&min_auto_bounds);
}
```

When `default_auto_bounds` is not set (`auto_bounds(false)`), and the bounds are unmodified via the PlotUi builder, then this resets the bounds to the defaults every frame instead of using the last frame bounds.  The single-frame offset from the drag/zoom/scroll is still applied, but since it always is starting from the defaults it jumps back as soon as you stop interacting with it.

### PR DESCRIPTION
**Pull request by kitizz**
The previous logic would force reset the bounds for an axis if its auto_bounds was false. I believe that the behavior of mem.auto_bounds already sufficiently achieves the intended behavior here.

Scenarios tested:
- User can pan/zoom/scroll with auto_bounds true/false
- Double-click resets auto_bounds the plot (regardless of default_auto_bounds setting)
- Plot bounds are updated when plot data changes after double-clicking
- User can still interact with the plot (pan/zoom/scroll) after double-clicking

* Closes #151
* [x] I have followed the instructions in the PR template

### CODE REVIEW

File: egui_plot/src/plot.rs [hunk 1]
```diff
@@ -1006,11 +1005,11 @@ impl<'a> Plot<'a> {
             }
         }
 
-        // Reset bounds to initial bounds if they haven't been modified.
-        if (!self.default_auto_bounds.x && !any_dynamic_modifications) || mem.auto_bounds.x {
```
Comment (kitizz) [inline egui_plot/src/plot.rs]: I hope my understanding of the full intention here is correct. I thought long and hard about it, and played around with a number of different configurations, and this works well.
But I'm suspicious that I'm missing something important

Comment (bircni) [reply egui_plot/src/plot.rs]: I could not find any problems here either

**Review by bircni — APPROVED** [review]
lgtm
Lets get this in prod and write an issue to write test once the kittest is added
